### ISSUE TITLE
freshTextureFloat internal format is not RGBA32F

### ISSUE THREAD

**Issue by Vizaxo** [acowley/GLUtil#30]
The `freshTextureFloat` function, which I expected to generate a texture with an internal format of 32-bit floats for each channel, instead had a format of 8-bit unsigned integers.

This is because the `PixelInternalFormat` is specified as `RGBA'`, which seems to indicate an 8-bit normalized internal format, rather than `RGBA32F` (in `Textures.hs`, line 114).

Is this intended behaviour, or should it be changed? Should an option for manually specifying the pixel format be added?

**Comment by acowley** [comment]
I think you're right that this is a bug. The `TexMono` case, for example, inspects the `pixelType` to decide if it should use something like an `R32F` internal format. The `TexRGBA` path should do the same. I think I probably use mono float textures too often.
